Maquiagro/Maquiagro/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include 
from core import views
from django.conf import settings
from django.conf.urls.static import static
from contactos import views as contactos_views
from portafolio import views as portafolio_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.inicio,name='inicio'),
    path('portafolio/',portafolio_views.portafolio,name='portafolio'),
    path('carrito/',include('carrito.urls')),
    path('pedidos/',include('pedidos.urls')),
    path('productos/',views.producto,name='productos'),
    path('servicio/',views.servicio,name='servicio'),

    path('contacto/',contactos_views.contacto,name='contacto'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('Registro/',views.registro,name='registro'),

    path('cambiar-contrasena/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('cambiar-contrasena/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('restablecer-contrasena/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('restablecer-contrasena/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('restablecer-contrasena/confirmar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('restablecer-contrasena/completar/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    
    ]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Maquiagro/carrito/urls.py
from django.urls import path
from .import views

app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),       
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),

]

Maquiagro/portafolio/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.portafolio, name="portafolio"),
]

Maquiagro/carrito/models.py
from django.db import models

# Create your models here.

Maquiagro/portafolio/models.py
from django.db import models
from django.utils.timezone import now
from core.models import category

class project(models.Model):
    title=models.CharField(max_length=50,verbose_name='Nombre')
    descripcion=models.TextField(verbose_name='Descripcion')
    image=models.ImageField(verbose_name='Imagen',upload_to='projects')
    marca=models.CharField(max_length=50,verbose_name='Marca')
    categories=models.ManyToManyField(category,max_length=20, verbose_name="categoria")
    price=models.FloatField(verbose_name='precio', null=True)
    created=models.DateTimeField(auto_now_add=True,verbose_name='Fecha Creacion') #añade de forma automatica
    updated=models.DateTimeField(auto_now=True,verbose_name="fecha de edicion")
    

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"
        ordering=["-created"] #ordena del nuevo al antiguo

    def __str__(self):
        return self.title

Maquiagro/carrito/views.py
from django.shortcuts import render
from .carrito import carrito
from portafolio.models import project
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request,producto_id):
    carro=carrito(request)
    producto=project.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("portafolio")

def eliminar_producto(request,producto_id):
    carro=carrito(request)
    producto=project.objects.get(id=producto_id)
    carro.eliminar(producto=producto) #solo se cambia la funcion agregar por la de eliminar que se creo en models.py
    return redirect("portafolio")

def restar_producto(request,producto_id):
    carro=carrito(request)
    producto=project.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("portafolio")

def limpiar_carro(request):

    carro = carrito(request)

    carro.limpiar_carro()

    return redirect("portafolio")

Maquiagro/portafolio/views.py
from django.shortcuts import render
from core.models import iconos
from .models import project
from core.models import category

def portafolio(request):
    redes=iconos.objects.all()
    projects=project.objects.all()
    categoria=category.objects.all()
    return  render(request,"portafolio/portafolio.html",{'projects':projects,'redes':redes,'categoria':categoria})

Maquiagro/portafolio/templates/carrito/widget.html
{% load static %}
{% load humanize %}
<style>
/* Estilos para pantallas medianas y grandes */
@media screen and (min-width: 768px) {
    .table-container {
        grid-template-columns: 1fr 300px;
    }
}
</style>

<body>
    <link rel="stylesheet" href="{% static 'css/msg.css'%}">
<div class="container" id="table-car">
    <div class="table-container">
        <div class="table-wrapper">
            <table class="table table-bordered">
                {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
                <thead>
                <tr>
                    <th colspan="3" class="text-center">
                        Carro compras
                    </th>
                </tr>
                <tr>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Suma</th>
                </tr>
                </thead>
                <tbody>
                {% if request.session.carrito.items %}
                    {% for key, value in request.session.carrito.items %}
                        <tr class="text-center">
                            <td>{{ value.nombre }}</td>
                            <td>{{ value.cantidad }}</td>
                            <td colspan="3">
                                <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success boton_sumar">+</a>
                                <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-danger boton_restar">-</a>
                                ${{ value.precio|floatformat:3|intcomma}} 
                            </td>
                        
                        </tr>
                    {% endfor %}
                    <tr>
                        <td style="text-align: center;" colspan="3">
                            <button class="btn btn-danger" data-toggle="modal" data-target="#confirmarVaciarCarro"><i class="bi bi-trash3-fill"></i>Eliminar Todo</button>
                        </td>
                        <div class="modal fade" id="confirmarVaciarCarro" tabindex="-1" role="dialog" aria-labelledby="confirmarVaciarCarroLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmarVaciarCarroLabel">Confirmar Vaciar Carro</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Estás seguro de que deseas vaciar el carrito?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <a href="{% url 'carro:limpiar' %}" class="btn btn-danger"><i class="bi bi-trash3-fill"></i>&emsp;Eliminar</a>
            </div>
        </div>
    </div>
</div>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="3">
                            <div class="alert alert-danger text-center">
                                Sin productos
                            </div>
                        </td>
                    </tr>
                {% endif %}
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3">
                        Total: $ {{ importe_total_carro|floatformat:3|intcomma }} pesos
                    </td>
                </tr>
                {% if request.session.carrito.items %}
                    <tr>
                        <td colspan="3" style="text-align: center;">
                            <a href="../pedidos" class="btn btn-success">Comprar</a>
                        </td>
                    </tr>
                {% endif %}
                </tfoot>
            </table>
        </div>
        
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function() {
        // Maneja el clic en el botón de sumar
        $(document).on("click", ".boton_sumar", function(event) {
          event.preventDefault();
          var url = $(this).attr("href");
      
          // Realiza una solicitud AJAX GET a la URL
          $.get(url, function(data) {
            // Actualiza solo la parte de la tabla del carrito
            $("#table-car").html($(data).find("#table-car").html());
          });
        });
      
        // Maneja el clic en el botón de restar (puedes hacer lo mismo para eliminar)
        $(document).on("click", ".boton_restar", function(event) {
          event.preventDefault();
          var url = $(this).attr("href");
      
          // Realiza una solicitud AJAX GET a la URL
          $.get(url, function(data) {
            // Actualiza solo la parte de la tabla del carrito
            $("#table-car").html($(data).find("#table-car").html());
          });
        });
  
        // Maneja el clic en el botón de sumar
        $(document).on("click", ".boton_eliminar", function(event) {
          event.preventDefault();
          var url = $(this).attr("href");
      
          // Realiza una solicitud AJAX GET a la URL
          $.get(url, function(data) {
            // Actualiza solo la parte de la tabla del carrito
            $("#table-car").html($(data).find("#table-car").html());
          });
        });
      });
</script>